---
- name : Configure webserver with nginx
  hosts: test
  become: yes

  tasks:
  - name: copy nginx config file
    copy:
      src: "files/nginx.conf" 
      dest: "/etc/nginx/conf.d/default.conf"


  - name: copy index.html
    template: 
      src: "templates/index.html.j2" 
      dest: "/usr/share/nginx/html/index.html"
      mode: 0644

